### ISSUE TITLE
为啥输入文件名回车没反应，github clone下来 f5也运行不了，报找不到vscode模块错误

### ISSUE THREAD

**Issue by 15206125206** [huangjianke/fish-redux-template#2]
为啥输入文件名回车没反应，github clone下来 f5也运行不了，报找不到vscode模块错误

**Comment by nslogx** [comment]
@15206125206 请问下你那边的版本是多少、环境是怎样的，方便的话贴个图看看

**Comment by 15206125206** [comment]
![image](https://user-images.githubusercontent.com/35686837/55778533-ba33c680-5ad5-11e9-88fd-7529238e0ab7.png)

**Comment by nslogx** [comment]
@15206125206 抱歉，我这边暂时没有在Windows_NT上试用，需要后续看看，欢迎PR

**Comment by 15206125206** [comment]
好的，那等大佬有时间看一下吧

**Comment by Notsfsssf** [comment]
Same in Windows_NT
