### ISSUE TITLE
Can't use in VS Code version (1.33.1)

### ISSUE THREAD

**Issue by dingchaoyan1983** [huangjianke/fish-redux-template#3]
This can be found in the vscode market, but my vscode version is 1.33.1, after installed successfully, but I can't use the extensions.

**Comment by nslogx** [comment]
@dingchaoyan1983 thanks, I will try later

**Comment by nslogx** [comment]
@dingchaoyan1983 
![image](https://user-images.githubusercontent.com/8692455/56777888-44826700-6806-11e9-908d-846a2243be4f.png)

I have already try in version 1.33.1, it's OK,
Would you please give me more information

**Comment by dingchaoyan1983** [comment]
Which extensions did you use? I used the latest version 0.5

**Comment by nslogx** [comment]
me too...
what’s your OS version

**Comment by dingchaoyan1983** [comment]
macOS sierra
10.12.6 (16G29)

**Comment by dingchaoyan1983** [comment]
and my mate install the extentions successfully too, but the menu dose not show the expected items too

**Comment by coldfox** [comment]
I have found the bug..
In The plugin file util.ts.. and the function generateFolderPath, change all url.path to uri.fsPath, it will be ok now...

**Comment by nslogx** [comment]
@coldfox @dingchaoyan1983 
version 0.0.6 was published，thanks @hzgotb
