### ISSUE TITLE
Can't use in ubuntu.

### ISSUE THREAD

**Issue by huang12zheng** [huangjianke/fish-redux-template#5]
版本: 1.34.0
提交: a622c65b2c713c890fcf4fbf07cf34049d5fe758
日期: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.8.0-59-generic

input Enter is no useful for Create Template.
And If I want to PR,Can you tell you how to do it ?

**Comment by nslogx** [comment]
Sorry, I have not use it in ubuntu yet

Welcome PR

**Comment by huang12zheng** [comment]
OK, Thank you all the same.
